name: Docker Build and Push on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read the version
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            erolatex/json-go-mimic:latest
            erolatex/json-go-mimic:${{ steps.version.outputs.VERSION }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
